import React from 'react';
import { FileText, ArrowRight } from 'lucide-react';

import { markdownToHtml, exportAnnexIVPdf } from '../lib/annexIVPdf.js';

// "Show, don't tell" section on the public landing page: a real Annex IV
// report rendered inline so a compliance officer can judge the artifact
// before creating an account. The markdown mirrors exactly what the
// scanner emits for a typical high-risk (Annex III — employment) system;
// keep it in sync with the template in lib/annexIV.js when sections
// change shape.
const SAMPLE_MARKDOWN = `# EU AI Act - Annex IV Technical Documentation

## 1. General System Description (Annex IV, Section 1)
- **System Name:** resume-screening-service
- **Version / Commit SHA:** \`9f2c41ab\`
- **Intended Purpose:** Automated ranking of job applications prior to human review (Annex III, 4(a) — employment; classified high-risk).

## 2. System Architecture & Components (Annex IV, Section 2)
### 2(a) Pre-trained Systems & Dependencies (AI-BOM)
- **transformers** (v4.44.2) [License: Apache-2.0]: Hugging Face model loading and inference (Risk: High)
- **torch** (v2.4.0) [License: BSD-3-Clause]: Tensor computation and model runtime (Risk: High)
- **langchain** (v0.2.14) [License: MIT]: LLM orchestration framework (Risk: High)
- **openai** (v1.40.1) [License: Apache-2.0]: Hosted LLM API client (Risk: Medium)
- **scikit-learn** (v1.5.1) [License: BSD-3-Clause]: Feature scoring pipeline (Risk: Medium)

### 2(c) Hardware Requirements & Estimated Monthly Cost (FinOps Telemetry)
- **Resource:** aws_instance.inference_node
  - **Finding:** GPU instance \`g5.2xlarge\` without autoscaling policy
  - **Estimated cost:** $1.21–$1.45 /hr → **$880–$1,050 /month** (AWS family \`g5\`)
  - **Spot/preemptible projection:** **$264–$315 /month** (30% of on-demand)

**Estimated total monthly cost:** $880–$1,050 USD (across 1 costed finding(s); 0 additional finding(s) had no catalog match).

## 3. Continuous Risk Management (Article 9 & Annex IV, Section 4)
**Current Automated Posture:** Passed

### 3(a) Cross-Referenced Risk Register (OWASP ML Top 10 / MITRE ATLAS)
| Component | Severity | OWASP ML Top 10 | MITRE ATLAS | AI Act | Live CVE/GHSA |
|---|---|---|---|---|---|
| \`transformers\` | High | ML06 — Supply Chain | AML.T0010 | Art. 15 | GHSA-x3r4-... |
| \`langchain\` | Critical | ML01 — Prompt Injection | AML.T0051 | Art. 9, 15 | CVE-2024-... |
| \`torch\` | High | ML05 — Model Theft | AML.T0044 | Art. 15 | — |

*Automated CI/CD Pipeline Controls:*
- [x] High-risk dependency constraints validated.
- [x] Prompt-injection defences detected: \`rebuff\`

## 4. Human Oversight & Data Governance (Annex IV, Section 3)
- **Human-in-the-loop (HITL) Controls:** 1 signal(s) detected — see evidence below.
  - GitHub Actions deployment gated on a protected environment _(source: github-actions, location: \`.github/workflows/deploy.yml\`)_
- **Training Data Provenance:** 1 signal(s) detected — see evidence below.
  - DVC-tracked dataset detected _(source: dvc, location: \`data/applicants.dvc\`)_
- **Bias Monitoring:** 1 signal(s) detected — see evidence below.
  - Fairlearn import found in evaluation pipeline _(source: python-import, location: \`eval/fairness_report.py\`)_
`;

export default function SampleReportSection() {
  return (
    <section
      id="sample-report"
      aria-labelledby="sample-report-heading"
      className="mt-24 pt-12 border-t border-slate-200"
    >
      <div className="text-center mb-10">
        <p className="text-sm font-bold text-indigo-600 uppercase tracking-widest mb-2">
          The Deliverable
        </p>
        <h2
          id="sample-report-heading"
          className="text-3xl lg:text-4xl font-extrabold text-slate-900"
        >
          This is what your auditor receives.
        </h2>
        <p className="text-slate-600 mt-3 max-w-2xl mx-auto">
          A complete Annex IV technical documentation draft — AI-BOM, Article 9
          risk register, GPU cost telemetry, and governance evidence — generated
          from a single CI run. Below is real scanner output for a high-risk
          hiring system.
        </p>
      </div>

      <div className="max-w-3xl mx-auto">
        <div className="relative bg-white rounded-2xl border border-slate-200 shadow-[0_8px_30px_rgb(0,0,0,0.08)] overflow-hidden">
          <div className="px-4 py-2 bg-slate-50 border-b border-slate-200 flex items-center justify-between">
            <span className="text-xs font-mono text-slate-500">
              docs/compliance/annex-iv.md
            </span>
            <span className="text-xs px-2 py-1 rounded text-emerald-700 bg-emerald-50 font-bold">
              Generated by aicap --cli
            </span>
          </div>
          <div
            className="annex-sample p-8 max-h-[32rem] overflow-hidden text-sm text-slate-700 [&_h1]:text-xl [&_h1]:font-extrabold [&_h1]:text-slate-900 [&_h1]:border-b-2 [&_h1]:border-indigo-500 [&_h1]:pb-2 [&_h2]:text-base [&_h2]:font-bold [&_h2]:text-slate-900 [&_h2]:mt-6 [&_h3]:text-sm [&_h3]:font-bold [&_h3]:text-slate-800 [&_h3]:mt-4 [&_p]:my-2 [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:my-2 [&_li]:my-1 [&_code]:bg-slate-100 [&_code]:px-1 [&_code]:rounded [&_code]:text-xs [&_code]:font-mono [&_table]:w-full [&_table]:text-xs [&_table]:my-3 [&_th]:border [&_th]:border-slate-300 [&_th]:bg-indigo-50 [&_th]:p-1.5 [&_th]:text-left [&_td]:border [&_td]:border-slate-200 [&_td]:p-1.5"
            // Safe by construction: SAMPLE_MARKDOWN is a local constant and
            // markdownToHtml escapes all content before adding markup.
            dangerouslySetInnerHTML={{ __html: markdownToHtml(SAMPLE_MARKDOWN) }}
          />
          {/* Fade-out so the capped preview reads as "there's more". */}
          <div className="absolute bottom-0 left-0 right-0 h-32 bg-gradient-to-t from-white to-transparent pointer-events-none" />
        </div>

        <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mt-8">
          <button
            onClick={() => exportAnnexIVPdf(SAMPLE_MARKDOWN, { projectName: 'sample-report' })}
            className="flex items-center gap-2 bg-slate-100 hover:bg-slate-200 text-slate-900 font-bold px-6 py-3 rounded-lg transition"
          >
            <FileText className="w-4 h-4" /> Download the sample as PDF
          </button>
          <a
            href="#signup"
            className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white font-bold px-6 py-3 rounded-lg transition shadow-md shadow-indigo-200"
          >
            Generate yours in one CI run <ArrowRight className="w-4 h-4" />
          </a>
        </div>
      </div>
    </section>
  );
}
