package scanner

import (
	"path/filepath"
	"testing"
)

// Each parser test uses a realistic snippet from the documented format
// and asserts that AI-relevant deps come back populated while irrelevant
// deps are silently dropped (we're an AI scanner, not a generic SBOM).

func TestParsePoetryLock_PicksUpAITorchEntries(t *testing.T) {
	path := createTempFile(t, "poetry.lock", `# This file is automatically generated, DO NOT EDIT.

[[package]]
name = "numpy"
version = "1.26.0"
description = "Fundamental package for array computing"

[[package]]
name = "torch"
version = "2.1.0"
description = "Tensors and Dynamic neural networks in Python"

[[package]]
name = "transformers"
version = "4.30.0"
description = "State-of-the-art Machine Learning"
`)
	deps := parsePoetryLock(path)
	if len(deps) != 2 {
		t.Fatalf("got %d deps, want 2 (torch + transformers; numpy not in catalog): %#v", len(deps), deps)
	}
	names := map[string]string{}
	for _, d := range deps {
		names[d.Name] = d.Version
	}
	if names["torch"] != "2.1.0" {
		t.Errorf("torch version = %q, want 2.1.0", names["torch"])
	}
	if names["transformers"] != "4.30.0" {
		t.Errorf("transformers version = %q, want 4.30.0", names["transformers"])
	}
}

func TestParsePipfileLock_PicksUpAIDeps(t *testing.T) {
	path := createTempFile(t, "Pipfile.lock", `{
  "_meta": {"hash": {"sha256": "..."}},
  "default": {
    "torch": {"version": "==2.1.0", "hashes": ["..."]},
    "requests": {"version": "==2.31.0"}
  },
  "develop": {
    "transformers": {"version": "==4.30.0"}
  }
}`)
	deps := parsePipfileLock(path)
	if len(deps) != 2 {
		t.Fatalf("got %d deps, want 2 (torch from default + transformers from develop): %#v", len(deps), deps)
	}
	names := map[string]string{}
	for _, d := range deps {
		names[d.Name] = d.Version
	}
	if names["torch"] != "2.1.0" {
		t.Errorf("torch version = %q (operator should be stripped)", names["torch"])
	}
}

func TestParsePnpmLock_PicksUpAIDeps(t *testing.T) {
	path := createTempFile(t, "pnpm-lock.yaml", `lockfileVersion: '6.0'
packages:
  /lodash@4.17.21:
    resolution: {integrity: sha512-x}
  /openai@4.52.5:
    resolution: {integrity: sha512-y}
  /@anthropic-ai/sdk@0.20.0:
    resolution: {integrity: sha512-z}
`)
	deps := parsePnpmLock(path)
	// targetAILibraries currently catalogs "openai" — @anthropic-ai/sdk
	// would only match if catalog has that scoped key. Spot-check
	// what we get back rather than over-asserting on catalog contents.
	gotOpenAI := false
	for _, d := range deps {
		if d.Name == "openai" && d.Version == "4.52.5" {
			gotOpenAI = true
		}
	}
	if !gotOpenAI {
		t.Errorf("expected openai@4.52.5 in pnpm output, got: %#v", deps)
	}
}

func TestParseYarnLock_PicksUpAIDeps(t *testing.T) {
	path := createTempFile(t, "yarn.lock", `# THIS IS AN AUTOGENERATED FILE.

"openai@^4.0.0":
  version "4.52.5"
  resolved "https://registry.yarnpkg.com/..."

"lodash@^4.17.21":
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/..."
`)
	deps := parseYarnLock(path)
	gotOpenAI := false
	for _, d := range deps {
		if d.Name == "openai" && d.Version == "4.52.5" {
			gotOpenAI = true
		}
	}
	if !gotOpenAI {
		t.Errorf("expected openai@4.52.5 in yarn.lock output, got: %#v", deps)
	}
}

func TestParseCondaEnv_PicksUpAIDeps(t *testing.T) {
	path := createTempFile(t, "environment.yml", `name: my-ai-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26.0
  - pip:
      - torch==2.1.0
      - transformers==4.30.0
`)
	deps := parseCondaEnv(path)
	names := map[string]string{}
	for _, d := range deps {
		names[d.Name] = d.Version
	}
	if names["torch"] != "2.1.0" {
		t.Errorf("expected torch=2.1.0 from pip sub-block, got: %#v", deps)
	}
	if names["transformers"] != "4.30.0" {
		t.Errorf("expected transformers=4.30.0 from pip sub-block, got: %#v", deps)
	}
}

func TestParseCondaEnv_StopsAtNextTopLevelKey(t *testing.T) {
	// If the parser failed to exit the dependencies: section, this
	// line ("variables:" with subsequent key=value pairs) might leak
	// into output. Confirms the section-toggle logic.
	path := createTempFile(t, "environment.yml", `dependencies:
  - torch==2.1.0
variables:
  HF_HOME: /opt/cache
`)
	deps := parseCondaEnv(path)
	if len(deps) != 1 || deps[0].Name != "torch" {
		t.Errorf("expected single torch entry, got: %#v", deps)
	}
}

// Integration: drop all five new manifest types into a temp project
// and run PerformScan end-to-end. Confirms the wiring in scanner.go's
// walk dispatches to each new parser.
func TestPerformScan_PicksUpNewManifestFormats(t *testing.T) {
	dir := createTempDir(t, map[string]string{
		"poetry.lock": `[[package]]
name = "torch"
version = "2.1.0"
`,
		"Pipfile.lock": `{
  "default": {"transformers": {"version": "==4.30.0"}},
  "develop": {}
}`,
		"pnpm-lock.yaml": `packages:
  /openai@4.52.5:
    resolution: {}
`,
		"yarn.lock": `"openai@^4.0.0":
  version "4.52.5"
`,
		"environment.yml": `dependencies:
  - pip:
      - langchain==0.1.0
`,
	})

	bom := PerformScan(dir)
	ecosystems := map[string]bool{}
	for _, d := range bom.Dependencies {
		ecosystems[d.Ecosystem] = true
	}
	for _, want := range []string{
		"Python (Poetry lock)",
		"Python (Pipfile lock)",
		"Node.js (pnpm lock)",
		"Node.js (yarn lock)",
		"Python (Conda environment.yml)",
	} {
		if !ecosystems[want] {
			t.Errorf("PerformScan missing ecosystem %q\nseen: %#v\npath: %s",
				want, ecosystems, filepath.Base(dir))
		}
	}
}
